sudo: required

language: ruby

services:
    - docker

before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - docker build -t spboyer/people-service .
    - docker tag spboyer/people-service:latest spboyer/people-service:v3
    - docker push spboyer/people-service